// src/app/r/[id]/page.tsx
'use client'
import { useEffect, useMemo } from 'react'

import { useRouter } from 'next/navigation'

import ArrowLongRightIcon from '@/shared/components/ui/icons/solid/arrow-long-right'
import { MemberMap } from '@/shared/constants/member'
import decodeShuffleMember from '@/shared/utils/decode-shuffle-member'
import getEncodeShuffleMember from '@/shared/utils/get-encode-shuffle-member'

type Props = {
  params: { id: string }
}

export default function RenderPage({ params: { id } }: Props) {
  const ids = useMemo(() => decodeShuffleMember(id), [id])
  const groups = useMemo(
    () =>
      ids?.map((item, index) => {
        const nextIdx = index + 1 < ids?.length ? index + 1 : 0
        const next = ids[nextIdx]

        return [item, next].map(val => MemberMap.get(val))
      }),
    [ids]
  )
  const router = useRouter()

  useEffect(() => {
    if (ids) return
    router.push(`/r/${getEncodeShuffleMember()}`)
  }, [ids, router])

  return (
    <div className="mt-8 flex items-center justify-center p-8">
      <ul className="grid gap-4">
        {groups?.map(([from, to]) => (
          <li
            key={`${from}-${to}`}
            className="grid grid-cols-3 gap-2 text-xl font-bold"
          >
            <p className="justify-self-end">{from}</p>
            <ArrowLongRightIcon className="h-6 w-6 justify-self-center" />
            <p className="justify-self-start">{to}</p>
          </li>
        ))}
      </ul>
    </div>
  )
}

// pages/r/[id].vue
<template>
  <main>
    <ul
      v-if="groups"
      class="flex flex-col gap-4 bg-gradient-to-b from-primary to-background py-8"
    >
      <li
        v-for="[from, to] in groups"
        :key="`${from}-${to}`"
        class="flex items-center justify-center gap-2"
      >
        <p>{{ from }}</p>
        <ArrowLongRight class="h-6 w-6" />
        <p>{{ to }}</p>
      </li>
    </ul>
  </main>
</template>

<script setup lang="ts">
import { watchEffect } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import ArrowLongRight from '~/components/icons/solid/arrow-long-right.vue'

import decodeShuffleMember from '~/utils/decode-shuffle-member'
import { MemberMap } from '~/constants/member'

const router = useRouter()

const {
  params: { id },
} = useRoute()

const ids = decodeShuffleMember(String(id))

watchEffect(() => {
  if (ids) {
    return
  }

  router.push({ name: 'index' })
})

const groups = ids?.map((item, index) => {
  const nextIdx = index + 1 < ids?.length ? index + 1 : 0
  const next = ids[nextIdx]

  return [item, next].map(val => MemberMap.get(val))
})
</script>
